### ISSUE TITLE
Deprecated: Creation of dynamic property Gridd\Updater::$ver is deprecated in /Updater.php on line 75

### ISSUE THREAD

**Issue by baikaresandip** [wplemon/github-theme-updater#3]
Hi, 
There is dynamic property deprecation warning for PHP 8.2.x version. 
`Deprecated: Creation of dynamic property Gridd\Updater::$ver is deprecated in /Updater.php on line 75`

**Comment by aristath** [comment]
Good catch! Thank you for the fix :+1:
